'use client';
import { useCallback,useEffect,useState } from 'react';
import { useAuth } from '@/lib/auth-provider';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { PageHeader } from '@/components/layout/page-header';
import { BadgeCheck,Copy,Loader2,RefreshCw,ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
type CodeResult={agent_code:string;full_name:string;code:string;expires_at:string;seconds_remaining:number};
export default function MyVerificationPage(){
 const {session}=useAuth();const [result,setResult]=useState<CodeResult|null>(null);const [seconds,setSeconds]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=useCallback(async()=>{if(!session?.access_token){setLoading(false);setError('Please sign in again to display your code.');return;}try{const res=await fetch('/api/agent-verification/code',{headers:{Authorization:'Bearer '+session.access_token},cache:'no-store'});const data=await res.json();if(!res.ok){setError(data.error||'No representative profile is linked to this account.');setResult(null);return;}setResult(data);setSeconds(data.seconds_remaining);setError('');}catch{setError('Verification service is temporarily unavailable.');}finally{setLoading(false);}},[session?.access_token]);
 useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(id);},[refresh]);
 useEffect(()=>{if(seconds<=0)return;const id=window.setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>window.clearInterval(id);},[seconds>0]);
 return <div className="mx-auto max-w-2xl space-y-6"><PageHeader title="My live verification code" description="Show this screen to a customer. Your six-digit code rotates every 30 seconds and is verified by the server." actions={<Button variant="outline" onClick={()=>void refresh()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}/>
 <Card className="overflow-hidden border-border/70"><div className="bg-gradient-to-br from-zinc-950 to-zinc-800 p-6 text-white sm:p-10"><div className="flex items-center gap-2 text-sm font-medium text-emerald-300"><ShieldCheck className="h-5 w-5"/>JCT live identity check</div>{loading?<div className="flex justify-center py-14"><Loader2 className="h-8 w-8 animate-spin"/></div>:error?<div className="py-10"><p className="font-semibold text-red-300">Code unavailable</p><p className="mt-2 text-sm text-zinc-300">{error}</p></div>:result&&<><p className="mt-6 text-sm text-zinc-300">{result.full_name}</p><p className="mt-1 font-mono text-xs text-zinc-400">{result.agent_code}</p><div className="mt-5 flex items-center justify-between gap-3"><div className="font-mono text-4xl font-bold tracking-[0.22em] sm:text-6xl">{result.code}</div><Button variant="secondary" size="icon" aria-label="Copy current code" onClick={()=>{void navigator.clipboard.writeText(result.code);toast.success('Current code copied');}}><Copy className="h-4 w-4"/></Button></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs text-zinc-300"><span>Code expires in</span><span>{seconds} seconds</span></div><div className="h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-emerald-400 transition-all duration-1000" style={{width:(seconds/30*100)+'%'}}/></div></div><p className="mt-5 text-xs leading-relaxed text-zinc-400">Keep this screen open when meeting a customer. A screenshot or previously copied code will expire and should not be accepted as proof.</p></>}</div></Card>
 <div className="flex items-start gap-3 rounded-xl border border-border p-4 text-sm text-muted-foreground"><BadgeCheck className="mt-0.5 h-5 w-5 shrink-0 text-primary"/><p>Customers can verify the representative ID and current code at the public <strong className="text-foreground">Verify company representative</strong> page. Never ask customers to pay personal accounts.</p></div></div>;
}
