'use client';
import { useCallback,useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase/client';
import { usePermissions } from '@/hooks/use-permissions';
import { PageHeader } from '@/components/layout/page-header';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Loader2,RefreshCw,Mail,Phone,MapPin,CarFront } from 'lucide-react';
import { toast } from 'sonner';
type Inquiry={id:string;inquiry_code:string;full_name:string;email:string;phone:string|null;company_name:string|null;destination_country:string|null;destination_port:string|null;vehicle_make:string|null;vehicle_model:string|null;year_from:number|null;year_to:number|null;budget_min:number|null;budget_max:number|null;currency:string;incoterm:string|null;quantity:number;message:string;status:string;assigned_to:string|null;created_at:string};
type Staff={id:string;full_name:string|null;email:string|null};
const statuses=['new','in_progress','quoted','converted','closed','spam'];
const styles:Record<string,string>={new:'bg-blue-500/10 text-blue-600',in_progress:'bg-amber-500/10 text-amber-600',quoted:'bg-emerald-500/10 text-emerald-600',converted:'bg-green-500/10 text-green-600',closed:'bg-muted text-muted-foreground',spam:'bg-red-500/10 text-red-600'};
export default function InquiriesPage(){
const {canView}=usePermissions();const [rows,setRows]=useState<Inquiry[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState('all');const [busy,setBusy]=useState('');const [staff,setStaff]=useState<Staff[]>([]);
const load=useCallback(async()=>{setLoading(true);let q=supabase.from('inquiries').select('*').order('created_at',{ascending:false}).limit(500);if(filter!=='all')q=q.eq('status',filter);const [{data,error},{data:profiles}] = await Promise.all([q,supabase.from('profiles').select('id,full_name,email').order('full_name')]);if(error)toast.error('Could not load inquiries: '+error.message);else setRows((data||[]) as Inquiry[]);setStaff((profiles||[]) as Staff[]);setLoading(false);},[filter]);useEffect(()=>{void load();},[load]);
const assign=async(id:string,userId:string)=>{setBusy(id);const {error}=await supabase.from('inquiries').update({assigned_to:userId==='unassigned'?null:userId,updated_at:new Date().toISOString()}).eq('id',id);setBusy('');if(error){toast.error('Could not assign inquiry: '+error.message);return;}toast.success('Inquiry owner updated');await load();};
const update=async(id:string,status:string)=>{setBusy(id);const dbStatus=status==='contacted'||status==='qualifying'?'in_progress':status;const {error}=await supabase.from('inquiries').update({status:dbStatus,updated_at:new Date().toISOString()}).eq('id',id);setBusy('');if(error){toast.error(error.message);return;}toast.success('Inquiry status updated');await load();};
if(!canView('customers'))return <div className="p-10 text-center text-muted-foreground">You do not have permission to view inquiries.</div>;
return <div className="space-y-6"><PageHeader title="Sales inquiries" description="Track public website requests from first contact through quotation and conversion." actions={<Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button>}/>
<div className="grid gap-3 sm:grid-cols-3"><Card className="p-4"><p className="text-sm text-muted-foreground">Total shown</p><p className="mt-1 text-2xl font-bold">{rows.length}</p></Card><Card className="p-4"><p className="text-sm text-muted-foreground">New inquiries</p><p className="mt-1 text-2xl font-bold">{rows.filter(r=>r.status==='new').length}</p></Card><Card className="p-4"><p className="text-sm text-muted-foreground">Quoted / converted</p><p className="mt-1 text-2xl font-bold">{rows.filter(r=>['quoted','converted'].includes(r.status)).length}</p></Card></div>
<div className="flex flex-wrap items-center gap-3"><span className="text-sm text-muted-foreground">Filter status</span><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All inquiries</SelectItem>{statuses.map(s=><SelectItem key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</SelectItem>)}</SelectContent></Select></div>
<Card className="overflow-hidden border-border/60">{loading?<div className="flex justify-center p-12"><Loader2 className="h-5 w-5 animate-spin"/></div>:rows.length===0?<div className="p-12 text-center text-sm text-muted-foreground">No inquiries yet. Website submissions will appear here.</div>:<div className="divide-y divide-border/70">{rows.map(r=><article key={r.id} className="space-y-4 p-4 md:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{r.full_name}</h2><Badge variant="outline" className={styles[r.status]||''}>{r.status}</Badge><span className="font-mono text-xs text-muted-foreground">{('JCT-INQ-'+String(r.inquiry_number).padStart(6,'0'))}</span></div><p className="mt-1 text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString()}{r.company_name?' · '+r.company_name:''}</p></div><Select value={r.status} disabled={busy===r.id} onValueChange={v=>void update(r.id,v)}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(s=><SelectItem key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</SelectItem>)}</SelectContent></Select><Select value={r.assigned_to||'unassigned'} disabled={busy===r.id} onValueChange={v=>void assign(r.id,v)}><SelectTrigger className="w-48"><SelectValue placeholder="Assign owner"/></SelectTrigger><SelectContent><SelectItem value="unassigned">Unassigned</SelectItem>{staff.map(p=><SelectItem key={p.id} value={p.id}>{p.full_name||p.email||p.id}</SelectItem>)}</SelectContent></Select></div>
<div className="flex flex-wrap gap-x-5 gap-y-2 text-sm"><a className="inline-flex items-center gap-1.5 text-primary" href={'mailto:'+r.email}><Mail className="h-3.5 w-3.5"/>{r.email}</a>{r.phone&&<a className="inline-flex items-center gap-1.5 text-primary" href={'tel:'+r.phone}><Phone className="h-3.5 w-3.5"/>{r.phone}</a>}{r.destination_country&&<span className="inline-flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5"/>{r.destination_country}{r.destination_port?', '+r.destination_port:''}</span>}{(r.vehicle_make||r.vehicle_model)&&<span className="inline-flex items-center gap-1.5"><CarFront className="h-3.5 w-3.5"/>{[r.vehicle_make,r.vehicle_model].filter(Boolean).join(' ')}</span>}</div>
<p className="whitespace-pre-wrap text-sm leading-relaxed">{r.message}</p><div className="flex flex-wrap gap-3 text-xs text-muted-foreground"><span>Qty: {r.quantity}</span><span>Term: {r.incoterms||'—'}</span>{r.budget_min!=null&&<span>Min: {r.currency} {Number(r.budget_min).toLocaleString()}</span>}{r.budget_max!=null&&<span>Max: {r.currency} {Number(r.budget_max).toLocaleString()}</span>}{r.year_from&&<span>Years: {r.year_from}{r.year_to?'–'+r.year_to:''}</span>}</div></article>)}</div>}</Card></div>;
}
