/*
# Customer CRM foundation

1. New Tables
- `customers`: Customer identity, contact details, lifecycle status, assignment, and notes.
- `customer_contacts`: Additional people connected to a customer account.
- `customer_requirements`: Vehicle requirements and budget targets for a customer.
- `customer_communications`: Call, email, WhatsApp, visit, and note timeline entries.

2. Modified Tables
- None. These tables are independent roots for later sales, quotations, invoices, and shipment records.

3. Security
- Row Level Security is enabled on all four tables.
- Assigned users can view and manage their customer records; administrators and auditors can view all records.
- Only administrators can delete customer records.
- Related records inherit access from their parent customer.

4. Important Notes
- Customer codes are generated by a database sequence-backed function and remain stable after creation.
- All timestamps are stored in UTC.
- The policies require an authenticated session and use the existing RBAC helper functions.
*/

CREATE SEQUENCE IF NOT EXISTS public.customer_code_seq START WITH 1001;

CREATE OR REPLACE FUNCTION public.next_customer_code()
RETURNS text
LANGUAGE sql
VOLATILE
SET search_path = public
AS $$
  SELECT 'JCT-C-' || nextval('public.customer_code_seq')::text;
$$;

CREATE TABLE IF NOT EXISTS public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_code text NOT NULL UNIQUE DEFAULT public.next_customer_code(),
  customer_type text NOT NULL DEFAULT 'individual' CHECK (customer_type IN ('individual', 'company')),
  full_name text NOT NULL,
  company_name text,
  email text,
  phone text,
  whatsapp text,
  country text,
  city text,
  address_line1 text,
  address_line2 text,
  tax_id text,
  default_currency text NOT NULL DEFAULT 'JPY',
  status text NOT NULL DEFAULT 'lead' CHECK (status IN ('lead', 'active', 'inactive', 'blocked')),
  source text,
  notes text,
  assigned_to uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_contacts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text,
  phone text,
  role text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_requirements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  make text,
  model text,
  year_from integer,
  year_to integer,
  budget_min numeric(14,2),
  budget_max numeric(14,2),
  currency text NOT NULL DEFAULT 'JPY',
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'matched', 'closed')),
  notes text,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.customer_communications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  communication_type text NOT NULL DEFAULT 'note' CHECK (communication_type IN ('call', 'email', 'whatsapp', 'visit', 'note')),
  subject text NOT NULL,
  body text,
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customers_assigned_to_idx ON public.customers(assigned_to);
CREATE INDEX IF NOT EXISTS customers_status_idx ON public.customers(status);
CREATE INDEX IF NOT EXISTS customers_country_idx ON public.customers(country);
CREATE INDEX IF NOT EXISTS customer_contacts_customer_id_idx ON public.customer_contacts(customer_id);
CREATE INDEX IF NOT EXISTS customer_requirements_customer_id_idx ON public.customer_requirements(customer_id);
CREATE INDEX IF NOT EXISTS customer_communications_customer_id_created_at_idx ON public.customer_communications(customer_id, created_at DESC);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_communications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "customers_select_assigned_or_admin" ON public.customers;
CREATE POLICY "customers_select_assigned_or_admin" ON public.customers FOR SELECT TO authenticated
USING (assigned_to = auth.uid() OR is_admin_user() OR has_role('auditor'));

DROP POLICY IF EXISTS "customers_insert_authenticated" ON public.customers;
CREATE POLICY "customers_insert_authenticated" ON public.customers FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid() AND (assigned_to IS NULL OR assigned_to = auth.uid() OR is_admin_user()));

DROP POLICY IF EXISTS "customers_update_assigned_or_admin" ON public.customers;
CREATE POLICY "customers_update_assigned_or_admin" ON public.customers FOR UPDATE TO authenticated
USING (assigned_to = auth.uid() OR is_admin_user())
WITH CHECK (assigned_to = auth.uid() OR is_admin_user());

DROP POLICY IF EXISTS "customers_delete_admin" ON public.customers;
CREATE POLICY "customers_delete_admin" ON public.customers FOR DELETE TO authenticated
USING (is_admin_user());

DROP POLICY IF EXISTS "customer_contacts_select_parent_access" ON public.customer_contacts;
CREATE POLICY "customer_contacts_select_parent_access" ON public.customer_contacts FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user() OR has_role('auditor'))));

DROP POLICY IF EXISTS "customer_contacts_insert_parent_access" ON public.customer_contacts;
CREATE POLICY "customer_contacts_insert_parent_access" ON public.customer_contacts FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_contacts_update_parent_access" ON public.customer_contacts;
CREATE POLICY "customer_contacts_update_parent_access" ON public.customer_contacts FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())))
WITH CHECK (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_contacts_delete_parent_access" ON public.customer_contacts;
CREATE POLICY "customer_contacts_delete_parent_access" ON public.customer_contacts FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_requirements_select_parent_access" ON public.customer_requirements;
CREATE POLICY "customer_requirements_select_parent_access" ON public.customer_requirements FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user() OR has_role('auditor'))));

DROP POLICY IF EXISTS "customer_requirements_insert_parent_access" ON public.customer_requirements;
CREATE POLICY "customer_requirements_insert_parent_access" ON public.customer_requirements FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid() AND EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_requirements_update_parent_access" ON public.customer_requirements;
CREATE POLICY "customer_requirements_update_parent_access" ON public.customer_requirements FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())))
WITH CHECK (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_requirements_delete_parent_access" ON public.customer_requirements;
CREATE POLICY "customer_requirements_delete_parent_access" ON public.customer_requirements FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_communications_select_parent_access" ON public.customer_communications;
CREATE POLICY "customer_communications_select_parent_access" ON public.customer_communications FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user() OR has_role('auditor'))));

DROP POLICY IF EXISTS "customer_communications_insert_parent_access" ON public.customer_communications;
CREATE POLICY "customer_communications_insert_parent_access" ON public.customer_communications FOR INSERT TO authenticated
WITH CHECK (created_by = auth.uid() AND EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_communications_update_parent_access" ON public.customer_communications;
CREATE POLICY "customer_communications_update_parent_access" ON public.customer_communications FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())))
WITH CHECK (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));

DROP POLICY IF EXISTS "customer_communications_delete_parent_access" ON public.customer_communications;
CREATE POLICY "customer_communications_delete_parent_access" ON public.customer_communications FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM public.customers c WHERE c.id = customer_id AND (c.assigned_to = auth.uid() OR is_admin_user())));
